apiVersion: 1
dataDisplay:
  showVerseInTuple: true
  textFormats:
    layout-orig-rich:
      method: layoutRich
      style: trans
    layout-orig-unicode:
      method: layoutUnicode
      style: orig
    text-orig-full:
      style: source
    text-orig-plain:
      style: trans
    text-orig-rich:
      style: trans
    text-orig-unicode:
      style: orig
docs:
  charText: mapping from readings to UNICODE
  charUrl: '{docBase}/programs/mapReadings.ipynb'
  docPage: about
  featureBase: '{docBase}/transcription{docExt}'
  featurePage: ''
interfaceDefaults:
  lineNumbers: false
provenanceSpec:
  corpus: 'Old Babylonian Letters 1900-1600: Cuneiform tablets '
  doi: 10.5281/zenodo.2579207
  org: Nino-cunei
  repo: oldbabylonian
  version: 1.0.5
  webBase: https://cdli.ucla.edu
  webHint: Show this document on CDLI
  webUrl: /search/search_results.php?SearchMode=Text&ObjectID=<1>
typeDisplay:
  cluster:
    children:
    - sign
    stretch: false
    label: '{type}'
  document:
    featuresBare: collection volume docnumber docnote
    lineNumber: srcLnNum
  face:
    featuresBare: object
    lineNumber: srcLnNum
  line:
    children:
    - cluster
    - word
    features: remarks translation@en
    lineNumber: srcLnNum
  sign:
    features: collated remarkable question damage det uncertain missing excised supplied
      langalt comment remarks repeat fraction operator grapheme
  word:
    base: true
    children:
    - cluster
    - sign
    label: true
    wrap: false
writing: akk
